# Generated by Django 3.1.3 on 2020-12-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageviewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Searches',
            new_name='Search',
        ),
    ]
