# Generated by Django 3.1.3 on 2020-12-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageviewer', '0003_auto_20201222_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
