# Generated by Django 3.1.3 on 2020-12-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageviewer', '0004_contact_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
